name: E2E Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Installation Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Installation packages
        run: npm i

      - name: Setup Allure CLI
        uses: allure-framework/setup-allure@v1
        with:
          allure-version: 2.35.1

      - name: Installation browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test --grep "@e2e"
        continue-on-error: true

      - name: Generate local Allure report
        run: allure generate allure-results --clean -o allure-report
        if: always()
        continue-on-error: true

      - name: Upload results to Allure TestOps
        if: always()
        continue-on-error: true
        run: |
          allure upload \
            --endpoint ${{ secrets.ALLURE_ENDPOINT }} \
            --project-id ${{ secrets.ALLURE_PROJECT_ID }} \
            --token ${{ secrets.ALLURE_TOKEN }} \
            --launch-name "E2E Tests - Build #${{ github.run_number }}" \
            --launch-tags "e2e,ui,github-actions,branch:${{ github.ref_name }}" \
            allure-results

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report-e2e
          path: allure-report
          retention-days: 30