name: E2E Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Installation Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Installation packages
        run: npm i

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Installation browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test --grep "@e2e"
        continue-on-error: true

      - name: Generate local Allure report
        run: allure generate allure-results --clean -o allure-report
        if: always()
        continue-on-error: true

      - name: Upload to Allure TestOps
        if: always()
        continue-on-error: true
        env:
          ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
        run: |
          tar -czf allure-results.tar.gz allure-results/
    
          curl -X POST \
            -H "Authorization: Api-Token $ALLURE_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            -F "file=@allure-results.tar.gz" \
            -F "projectId=$ALLURE_PROJECT_ID" \
            -F "launchName=E2E Tests - Build #${{ github.run_number }}" \
            "$ALLURE_ENDPOINT/api/v1/launch/upload"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report-e2e
          path: allure-report
          retention-days: 30