name: E2E Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Installation Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Installation packages
        run: npm ci

      - name: Installation browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test --grep "@e2e"
        continue-on-error: true

      - name: Install Allurectl
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/allure-framework/allurectl/releases/latest \
            | grep browser_download_url \
            | grep linux \
            | cut -d '"' -f 4)
          echo "Downloading: $DOWNLOAD_URL"
          curl -sLo allurectl "$DOWNLOAD_URL"
          chmod +x allurectl
          sudo mv allurectl /usr/local/bin/
          allurectl --version

      - name: Upload results to Allure TestOps
        if: always()
        env:
          ALLURE_ENDPOINT: ${{ secrets.ALLURE_ENDPOINT }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}
        run: |
          allurectl upload \
            --endpoint "$ALLURE_ENDPOINT" \
            --token "$ALLURE_TOKEN" \
            --project-id "$ALLURE_PROJECT_ID" \
            --launch "E2E Tests - Build #${{ github.run_number }}" \
            allure-results

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report-e2e
          path: allure-results
          retention-days: 30