name: E2E Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Installation Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Installation packages
        run: npm i

      - name: Installation browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test --grep "@e2e"
        continue-on-error: true

      - name: Upload results to Allure TestOps
        uses: allure-framework/allure-testops-action@v1
        if: always()
        with:
          allure-server-url: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
          allure-results: allure-results

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report-e2e
          path: allure-results
          retention-days: 30